closure<-read.csv("closure.csv",stringsAsFactors = F)
handover<-read.csv("handover.csv",stringsAsFactors = F)
dispatch<-read.csv("dispatch.csv",stringsAsFactors = F)
pending<-read.csv("pending.csv",stringsAsFactors = F)
library(dplyr)
pending %>% select(cs.st,cs.ss) %>% unique()
handover_fresh<-handover %>% select(Waybill,PackageType) %>% group_by(PackageType) %>% summarise(num_packages = length(Waybill)) %>% as.data.frame()
handover_totalnum<- handover_fresh %>% summarise(num_packages=sum(num_packages)) %>% as.data.frame() %>% mutate(PackageType="total") %>% select(PackageType,num_packages)
handover_fresh<- rbind(handover_fresh,handover_totalnum)
ncol(handover)
dispatch_count<- nrow(dispatch)
nrow(dispatch)
shipments_dispatched<- dispatch %>% summarise(total_dispatched=sum(as.numeric(Total)))
Shipments_delivered<- dispatch %>% summarise(total_delivered=sum(Delivered,Pickedup))
shipments_closed<- dispatch %>% summarise(total_closed=sum(Delivered,Pickedup,Returned,Collected))
handover <- handover %>% mutate(Promise.Date = as.POSIXct(strptime(Promise.Date,"%Y/%m/%d %H:%M:%S")))
handover$pdd<-substr(handover$Promise.Date,1,11)
pdd_count<- handover %>% select(Waybill,pdd) %>% group_by(pdd) %>% summarise(num_pdd= length(Waybill)) %>% as.data.frame()
pdd_breach<- handover %>% filter(pdd=="2017-03-09") %>% select(Waybill,DispatchCount) %>% group_by(DispatchCount) %>% summarise(breached_shipments=length(Waybill)) %>% as.data.frame()
